"""Initial shared collection schema, frozen independently of application models."""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bears',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_key', sa.Text(), nullable=False),
    sa.Column('oriented_key', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('detection_state', sa.String(), nullable=False),
    sa.Column('pipeline', sa.Text(), nullable=False),
    sa.Column('detections', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('jobs',
    sa.Column('photo_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('pipeline', sa.Text(), nullable=False),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_photo_id'), 'jobs', ['photo_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('observations',
    sa.Column('photo_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('box', sa.JSON(), nullable=False),
    sa.Column('crop_key', sa.Text(), nullable=False),
    sa.Column('pipeline', sa.Text(), nullable=False),
    sa.Column('recognition_state', sa.String(), nullable=False),
    sa.Column('review_state', sa.String(), nullable=False),
    sa.Column('bear_id', sa.String(length=36), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bear_id'], ['bears.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'index')
    )
    op.create_index(op.f('ix_observations_photo_id'), 'observations', ['photo_id'], unique=False)
    op.create_table('attempts',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_attempts_job_id'), 'attempts', ['job_id'], unique=False)
    op.create_table('reviews',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('bear_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bear_id'], ['bears.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_observation_id'), 'reviews', ['observation_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline', sa.Text(), nullable=False),
    sa.Column('gallery_revision', sa.Integer(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_observation_id'), 'suggestions', ['observation_id'], unique=False)
    # ### end Alembic commands ###
    op.execute('INSERT INTO gallery (id, revision) VALUES (1, 0)')


def downgrade():
    raise RuntimeError('Destructive downgrade disabled; restore a verified backup instead')
