import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {QueryClient, QueryClientProvider, useQuery} from '@tanstack/react-query';
import {Alert, AppBar, Box, Button, Card, CardContent, Chip, Container, CssBaseline, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Select, Stack, Tab, Tabs, TextField, ThemeProvider, Toolbar, Typography, createTheme} from '@mui/material';
const qc = new QueryClient();
const theme = createTheme({palette:{primary:{main:'#315a46'},background:{default:'#f5f4ef'}},shape:{borderRadius:12},typography:{fontFamily:'Inter, system-ui, sans-serif'}});
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
  const r=await fetch(path,{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:body===undefined?undefined:JSON.stringify(body)});
  if(!r.ok) throw new Error((await r.text()) || r.statusText); return r.json();
}
type Bear={id:string;name:string|null};
type Candidate={bear_id:string;name:string|null;reference_id:string;cosine:number};
type Head={id:string;index:number;box:number[];crop_url:string;recognition_state:string;review_state:string;bear_id:string|null;error:string|null;suggestions:{id:string;created_at:string;gallery_revision:number;candidates:Candidate[]}[]};
type Photo={id:string;filename:string;image_url:string;width:number;height:number;detection_state:string;pipeline:string};
type Detail=Photo&{heads:Head[];jobs:{id:string;stage:string;state:string;error:string|null;attempts:number}[]};
const label=(b:Bear)=>b.name||`Unnamed bear · ${b.id.slice(0,8)}`;
function App(){
 const [tab,setTab]=useState(0),[selected,setSelected]=useState(''),[index,setIndex]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [bearChoice,setBearChoice]=useState(''),[dialog,setDialog]=useState<'create'|'rename'|null>(null),[name,setName]=useState(''),[bearView,setBearView]=useState('');
 const health=useQuery({queryKey:['health'],queryFn:()=>api<{pipeline:string;commit:string}>('/health')});
 const photos=useQuery({queryKey:['photos'],queryFn:()=>api<Photo[]>('/api/photos'),refetchInterval:3000});
 const bears=useQuery({queryKey:['bears'],queryFn:()=>api<Bear[]>('/api/bears')});
 const detail=useQuery({queryKey:['photo',selected],queryFn:()=>api<Detail>('/api/photos/'+selected),enabled:!!selected,refetchInterval:2000});
 const refs=useQuery({queryKey:['refs',bearView],queryFn:()=>api<Head[]>(`/api/bears/${bearView}/references`),enabled:!!bearView});
 const head=detail.data?.heads[index];
 const history=useQuery({queryKey:['history',head?.id],queryFn:()=>api<{id:string;state:string;bear_id:string|null;created_at:string}[]>(`/api/heads/${head!.id}/history`),enabled:!!head});
 async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn();await qc.invalidateQueries();}catch(e){setError(String(e));}finally{setBusy(false);}}
 function review(state:string,bear_id?:string){if(head)void act(()=>api(`/api/heads/${head.id}/review`,'POST',{state,bear_id:bear_id||null}));}
 const currentError=error||String(photos.error||detail.error||bears.error||health.error||'');
 return <><AppBar position="static" elevation={0}><Toolbar><Typography variant="h6" sx={{flex:1}}>Only Bears</Typography><Chip label={health.data?.pipeline||'Connecting'} color="default"/></Toolbar></AppBar><Container maxWidth="lg" sx={{py:4}}><Stack spacing={3}>
 <Box><Typography variant="h4">A shared field notebook</Typography><Typography color="text.secondary">Upload photos, review detected heads, then match against confirmed references.</Typography></Box>
 {health.data?.pipeline.startsWith('mock')&&<Alert severity="warning">Mock inference — fixture results for local development. These references are separate from real inference.</Alert>}
 {currentError&&<Alert severity="error" onClose={()=>setError('')}>{currentError}</Alert>}{notice&&<Alert onClose={()=>setNotice('')}>{notice}</Alert>}
 <Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="Photos & review"/><Tab label="Bears & references"/></Tabs>
 {tab===0?<><Button variant="contained" component="label" disabled={busy}>Upload JPEG / PNG<input hidden multiple type="file" accept="image/jpeg,image/png" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;void act(async()=>{const form=new FormData();files.forEach(f=>form.append('files',f));const result=await api<{photos:(Photo&{error?:string;duplicate?:boolean})[]}>('/api/photos','POST',form);setNotice(result.photos.map(p=>`${p.filename}: ${p.error||(p.duplicate?'already uploaded':'saved')}`).join('; '));const first=result.photos.find(p=>p.id);if(first){setSelected(first.id);setIndex(0);}});}}/></Button>
 {!photos.data?.length&&<Alert severity="info">Start with a few photos. Confirming a head’s identity creates a reference for later matching. An empty candidate list does not establish a new individual.</Alert>}
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'240px 1fr'},gap:3}}><Stack spacing={1}>{photos.data?.map(p=><Button key={p.id} variant={selected===p.id?'contained':'outlined'} sx={{justifyContent:'start',textAlign:'left'}} onClick={()=>{setSelected(p.id);setIndex(0);setBearChoice('');}}>{p.filename}</Button>)}</Stack>
 {detail.data&&<Stack spacing={2}><Typography variant="h5">{detail.data.filename}</Typography><Typography>{detail.data.detection_state==='complete'?(detail.data.heads.length?'Awaiting head review — recognition runs only when requested':'No head detected'):detail.data.detection_state==='failed'?'Detection failed':'Detecting'}</Typography>
 <Box sx={{position:'relative'}}><img src={detail.data.image_url} alt="Oriented original" style={{width:'100%',display:'block',borderRadius:12}}/>{detail.data.heads.map((h,i)=><Box key={h.id} onClick={()=>{setIndex(i);setBearChoice('');}} sx={{position:'absolute',cursor:'pointer',border:`3px solid ${i===index?'#ffcc44':'#fff'}`,left:`${100*h.box[0]/detail.data!.width}%`,top:`${100*h.box[1]/detail.data!.height}%`,width:`${100*(h.box[2]-h.box[0])/detail.data!.width}%`,height:`${100*(h.box[3]-h.box[1])/detail.data!.height}%`}}><Chip size="small" label={i+1} sx={{background:'#ffcc44'}}/></Box>)}</Box>
 {!!detail.data.heads.length&&<><Alert severity="info">Review each numbered head. Ignore cubs or mark unusable crops before running recognition on the remaining heads.</Alert><Button disabled={busy||!detail.data.heads.some(h=>['not_requested','failed'].includes(h.recognition_state)&&!['ignored','unusable'].includes(h.review_state))} variant="contained" onClick={()=>act(()=>api(`/api/photos/${selected}/recognize`,'POST'))}>Run recognition</Button></>}
 {detail.data.jobs.filter(j=>j.error).map(j=><Alert key={j.id} severity={j.state==='failed'?'error':'warning'}>{j.stage}: {j.error} (attempts: {j.attempts}, {j.state}) {j.state==='failed'&&j.stage==='detection'&&<Button disabled={busy} onClick={()=>act(()=>api(`/api/jobs/${j.id}/retry`,'POST'))}>Retry detection</Button>}</Alert>)}
 {head&&<Card><CardContent><Stack spacing={2}><Stack direction="row" alignItems="center" justifyContent="space-between"><Button disabled={index===0} onClick={()=>{setIndex(index-1);setBearChoice('');}}>Previous</Button><Typography>Detected head {index+1} / {detail.data.heads.length}</Typography><Button disabled={index===detail.data.heads.length-1} onClick={()=>{setIndex(index+1);setBearChoice('');}}>Next</Button></Stack><img src={head.crop_url} alt={`Head ${index+1}`} style={{maxHeight:260,objectFit:'contain'}}/>
 <Typography>Recognition: {head.recognition_state} · Review: {head.review_state}{head.bear_id?` — ${label(bears.data?.find(b=>b.id===head.bear_id)||{id:head.bear_id,name:null})}`:''}</Typography>{head.error&&<Alert severity="error">{head.error}. Run recognition again to retry this eligible head.</Alert>}
 <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap">{['unresolved','ignored','unusable'].map(state=><Button key={state} disabled={busy} onClick={()=>review(state)}>{state==='unresolved'?'Leave unresolved':state==='ignored'?'Ignore subject':'Mark unusable'}</Button>)}</Stack>
 {head.recognition_state==='complete'&&<><Typography variant="h6">Candidate bears</Typography><Typography variant="body2">Cosine similarity compares image features; it is not identity probability. Bears with more references may be favored.</Typography>{!head.suggestions[0]?.candidates.length&&<Alert severity="info">No eligible confirmed references yet. Choose an existing bear, create a distinct named or unnamed identity, or leave unresolved.</Alert>}
 <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap">{head.suggestions[0]?.candidates.map(c=><Card variant="outlined" key={c.bear_id} sx={{width:170}}><img src={`/api/heads/${c.reference_id}/image`} alt="Supporting confirmed reference" style={{width:'100%',height:120,objectFit:'contain'}}/><CardContent><Typography>{label({id:c.bear_id,name:c.name})}</Typography><Typography variant="caption">Cosine similarity: {c.cosine.toFixed(4)}</Typography><Button disabled={busy} onClick={()=>review('confirmed',c.bear_id)}>Confirm</Button></CardContent></Card>)}</Stack>
 <Typography variant="caption">Saved snapshot revision {head.suggestions[0]?.gallery_revision} · {head.suggestions.length} snapshot(s)</Typography><Button disabled={busy} onClick={()=>act(()=>api(`/api/heads/${head.id}/refresh`,'POST'))}>Refresh candidates</Button></>}
 <Select displayEmpty value={bearChoice} onChange={e=>setBearChoice(e.target.value)}><MenuItem value="">Choose an existing bear</MenuItem>{bears.data?.map(b=><MenuItem key={b.id} value={b.id}>{label(b)}</MenuItem>)}</Select><Button disabled={busy||!bearChoice} onClick={()=>review('confirmed',bearChoice)}>Assign selected bear</Button><Button disabled={busy} onClick={()=>{setName('');setDialog('create');}}>Create named or unnamed bear & assign</Button>
 {!!history.data?.length&&<Box><Typography variant="subtitle2">Review history</Typography>{history.data.map(r=><Typography variant="caption" display="block" key={r.id}>{new Date(r.created_at).toLocaleString()} · {r.state}{r.bear_id?` · ${r.bear_id.slice(0,8)}`:''}</Typography>)}</Box>}
 </Stack></CardContent></Card>}
 </Stack>}</Box></>:<Stack spacing={2}><Typography>Confirmed usable heads with valid embeddings become references. Bear IDs remain stable when names change.</Typography>{bears.data?.map(b=><Button key={b.id} variant={bearView===b.id?'contained':'outlined'} onClick={()=>setBearView(b.id)}>{label(b)}</Button>)}{bearView&&<><Button onClick={()=>{setName(bears.data?.find(b=>b.id===bearView)?.name||'');setDialog('rename');}}>Edit display name</Button><Stack direction="row" spacing={2} useFlexGap flexWrap="wrap">{refs.data?.map(h=><img key={h.id} src={h.crop_url} alt="Confirmed reference" style={{height:160}}/>)}</Stack>{!refs.data?.length&&<Alert severity="info">No eligible references for this bear yet.</Alert>}</>}</Stack>}
 <Typography variant="caption" color="text.secondary">Head detection runs directly on oriented originals, with no body detector or crop margin. Matching quality is experimental. One shared collection; no automatic identity assignments.</Typography>
 </Stack></Container><Dialog open={!!dialog} onClose={()=>setDialog(null)}><DialogTitle>{dialog==='create'?'Create a distinct bear':'Edit display name'}</DialogTitle><DialogContent><TextField autoFocus label="Display name (optional)" value={name} inputProps={{maxLength:120}} onChange={e=>setName(e.target.value)} sx={{mt:1}}/><Typography variant="body2">Leave blank for an unnamed identity. “Unknown” is not a shared identity.</Typography></DialogContent><DialogActions><Button onClick={()=>setDialog(null)}>Cancel</Button><Button disabled={busy} onClick={()=>act(async()=>{if(dialog==='create'){const b=await api<Bear>('/api/bears','POST',{name:name||null});await api(`/api/heads/${head!.id}/review`,'POST',{state:'confirmed',bear_id:b.id});}else await api(`/api/bears/${bearView}`,'PATCH',{name:name||null});setDialog(null);})}>Save</Button></DialogActions></Dialog></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={qc}><ThemeProvider theme={theme}><CssBaseline/><App/></ThemeProvider></QueryClientProvider></React.StrictMode>);
